#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

export PRV_INCLUDE="${PRV_INCLUDE-/usr/local/lib}"

MACHTYPE="$(uname -m)"
case "${MACHTYPE}" in
  armv6l) ;&
  armv7l) MACHTYPE=arm ;;
  *) ;;
esac

PRV_LDFLAGS="-I$PRV_INCLUDE/kernel-headers/generic/include -I$PRV_INCLUDE/kernel-headers/${MACHTYPE}/include" CC="musl-gcc -static -Os" make $@
